server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/plugin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.mybatis.main.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


plugin:
  runMode: dev
  pluginPath: ./example/integration-mybatis/plugins
  pluginConfigFilePath: