server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/plugin_tkmybatis?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

plugin:
  runMode: dev
  pluginPath: ./example/integration-tkmybatis/plugins
  pluginConfigFilePath: